version: 0.2
env:
  secrets-manager:
    LOGIN: prod/sonar:sonartoken
    HOST: prod/sonar:HOST
    Organization: prod/sonar:Organization
    Project: prod/sonar:Project
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install pytest
  build:
    commands:
      - pytest test_DMDOMITINV00091125.py --junitxml=report.xml

artifacts:
  files:
    - '**/*'
  discard-paths: yes

reports:
  pytest_reports:
    files:
      - 'report.xml'
    discard-paths: yes
