version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install pytest
      - pip install boto3
  build:
    commands:
      - pytest tests/test_scripts.py --junitxml=report.xml
      - python tests/send_email_report.py

artifacts:
  files:
    - '**/*'
  discard-paths: yes

reports:
  pytest_reports:
    files:
      - 'report.xml'
    discard-paths: yes
